version: '3'

services:
  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: authentication
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    mem_limit: 512m

# sudo systemctl start docker.service